#!/usr/bin/env python3
"""
Helper script to automatically register test functions in test_suite.c

This script scans for test_*.c files and generates the registration code
needed in test_suite.c.

Usage:
    python3 tools/register_tests.py > test_registrations.inc
    Then include test_registrations.inc in test_suite.c

Or use it manually to see what registrations are needed.
"""

import os
import re
import sys
import glob


def find_test_files(src_dir="src"):
    """Find all test_*.c files."""
    pattern = os.path.join(src_dir, "test_*.c")
    test_files = glob.glob(pattern)
    # Filter out test_suite.c
    test_files = [f for f in test_files if "test_suite.c" not in f]
    return sorted(test_files)


def extract_test_registration(filepath):
    """Extract the test registration function name from a test file."""
    with open(filepath, "r") as f:
        content = f.read()

    # Look for TEST_SUITE_BEGIN(name) pattern
    match = re.search(r"TEST_SUITE_BEGIN\s*\(\s*(\w+)\s*\)", content)
    if match:
        suite_name = match.group(1)
        # Convert to registration function name
        # TEST_SUITE_BEGIN(ch_example) -> register_ch_example_tests
        return f"register_{suite_name}_tests"

    # Fallback: try to find register_*_tests function definition
    match = re.search(r"register_(\w+)_tests\s*\(", content)
    if match:
        return f"register_{match.group(1)}_tests"

    return None


def generate_registrations(tests_dir="tests"):
    """Generate registration code for all test files."""
    test_files = find_test_files(tests_dir)
    registrations = []

    print("// Auto-generated test registrations - Do not edit manually")
    print("// Generated by tools/register_tests.py\n")

    # Generate extern declarations
    for test_file in test_files:
        reg_func = extract_test_registration(test_file)
        if reg_func:
            print(f"extern void {reg_func}(void);")
            registrations.append(reg_func)

    print("\n// Registration calls (add these to main()):")
    for reg_func in registrations:
        print(f"    {reg_func}();")

    print(f"\n// Total: {len(registrations)} test suite(s) found")


if __name__ == "__main__":
    tests_dir = sys.argv[1] if len(sys.argv) > 1 else "tests"
    generate_registrations(tests_dir)
